### ISSUE TITLE
Erro com o postgress

### ISSUE THREAD

**Issue by Larileonell** [cami-la/academia-digital#33]
estou com esse errro e não estou conseguindo resolver
org.postgresql.util.PSQLException: O servidor pediu autenticação baseada em senha, mas nenhuma senha foi fornecida.
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:643) ~[postgresql-42.3.1.jar:42.3.1]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:163) ~[postgresql-42.3.1.jar:42.3.1]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:215) ~[postgresql-42.3.1.jar:42.3.1]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[postgresql-42.3.1.jar:42.3.1]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225) ~[postgresql-42.3.1.jar:42.3.1]
	at org.postgresql.Driver.makeConnection(Driver.java:466) ~[postgresql-42.3.1.jar:42.3.1]

**Comment by Larileonell** [comment]
consegui
